### ISSUE TITLE
Create a protocol.json validator & a UI for creating these

### ISSUE THREAD

**Issue by afolarin** [RADAR-base/RADAR-aRMT-protocols#10]
It would be quite a good idea to have a validator for the protocols in the event that it is released broken, this can result in substantial adverse experience for the aRMT. Could even be a done with Travis to validate the updates to the protocol files and prevent merging into master if it's broken.

- [x] validate JSON
- [x] validate protocol blocks
- [ ] validate times
- [ ] Furthermore, it would be very useful to build this into a User Interface for creating the protocols e.g. specify the timepoints you want the notifications and it would show you where they are going to be delivered. 
- [ ] It *might* be an idea eventually for the Management Portal or Dashboard to display the schedule of notifications, in this way it's easier for study management to review

**Comment by blootsvoets** [comment]
Building protocols via web-interface is a proposal at RADAR-base/radar-app-config#19. The other points (except time validation) are done.
