### ISSUE TITLE
Create notification text properties

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-base/RADAR-aRMT-protocols#14]
Ideally, the text and contents of notifications are customisable per questionnaire protocol. This would hold for initial notifications but also for reminders. In all, I would propose three variables: `notificationText`, `reminderText`, `lastReminderText`, each with per-language data.

**Comment by afolarin** [comment]
Agree this would be nice. One might even go a step further and allow per notification customisation (or the possibility to extend a default)?

**Comment by blootsvoets** [comment]
Ok that makes sense. Perhaps we can replace the `reminders` object with an array. Each would have
a `offset: {unit: 'day', amount: 1}` property for the timing and 'title' and 'text' properties for multi-lingual text.

**Comment by blootsvoets** [comment]
This is done.
