### ISSUE TITLE
Timeout of a questionnaire should be configurable in protocols

### ISSUE THREAD

**Issue by afolarin** [RADAR-base/RADAR-aRMT-protocols#7]
The current timeout (window which you can fill out a questionnaire) e.g. 10mins for ESM should be configurable on a project basis as a responsibility of the protocol.json protocol block rather than hard-coded in the RADAR-Questionnaire code.

**Comment by blootsvoets** [comment]
[Wiki documentation](https://radar-base.atlassian.net/wiki/spaces/RAD/pages/463241217/Protocol+Schedule) mentions a tentative `completionWindow` variable for this.

**Comment by blootsvoets** [comment]
This is done.
