### ISSUE TITLE
Language compatibility issue: special characters

### ISSUE THREAD

**Issue by JeroenDMW** [RADAR-base/RADAR-aRMT-protocols#89]
In the protocol you can specify reminder text of notifications (for example see https://github.com/JeroenDMW/RADAR-aRMT-protocols/blob/master/DynaMORE/protocol.json). I noticed that this is not yet compatible with special characters (e.g. special characters in polish / Hebrew alphabet).  

Is this something that can be fixed without requiring an app update?

@mpgxvii 

<img src="https://user-images.githubusercontent.com/16977973/99659821-67393800-2a9c-11eb-893e-828474789cb1.png" width="250">

_EDIT: Added screenshot for reference_

**Comment by afolarin** [comment]
@mpgxvii I assuming these lines here https://github.com/JeroenDMW/RADAR-aRMT-protocols/blob/0a115bba82f8f5318e94310108c1fe19d24f9dab/DynaMORE/protocol.json#L132-L137

**Comment by JeroenDMW** [comment]
> @mpgxvii I assuming these lines here https://github.com/JeroenDMW/RADAR-aRMT-protocols/blob/0a115bba82f8f5318e94310108c1fe19d24f9dab/DynaMORE/protocol.json#L132-L137

That's correct :)

**Comment by blootsvoets** [comment]
Moved issue to https://github.com/RADAR-base/RADAR-Questionnaire/issues/1305.
